#! /bin/sh
set -e

# Copy public files into a directory structure that we will mirror
# exactly in our S3 bucket used to serve pages for http://esper.co/

# List of files to install
html="index.html aboutus.html privacypolicy.html termsofuse.html jobs.html"
css="*.css"
fonts="*.eot *.svg *.ttf *.woff"
img="*.jpg *.svg *.ico *.png"
js="*.js"

rm -rf pub
mkdir -p pub

# HTML files go to directly under the server root (https://esper.com/...)
for x in $html; do
    cp html/$x pub/$x
done

# Other files go into /css, /img, /js

mkdir -p pub/css
for x in $css; do
    cp css/$x pub/css
done

mkdir -p pub/fonts
for x in $fonts; do
    cp fonts/$x pub/fonts
done

mkdir -p pub/img
for x in $img; do
    cp img/$x pub/img
done

mkdir -p pub/js
for x in $js; do
    cp js/$x pub/js
done
